### ISSUE TITLE
TASK - Design Text Search fucntionality UI

### ISSUE THREAD

**Issue by austinhedrick548** [kelseyp/munch#43]
Create a design document laying out an item card and details about its constituent parts.

**Comment by austinhedrick548** [comment]
Also should include "Toggle button between grid cards and table views on main page" in sketch.

**Comment by NathanaelPaulus** [comment]
Prototype designs. Search Bar in the app bar.
Then the view toggle in the top left corner of the info area.


![Image](https://user-images.githubusercontent.com/123440471/227051897-fb1d1d3b-d6e0-4b01-a72f-d96adbe0a5bb.jpg)


![Image](https://user-images.githubusercontent.com/123440471/227051792-2a1aa003-ff07-45ba-a49f-71aa306cd231.jpg)

**Comment by NathanaelPaulus** [comment]
Updated it with some more detail at Austin's request
![Image](https://user-images.githubusercontent.com/123440471/227061281-660a4f2e-1e27-4590-a493-1f3d4df367eb.jpg)

**Comment by austinhedrick548** [comment]
Looks good to me
