### ISSUE TITLE
TASK - Design item card for grid view

### ISSUE THREAD

**Issue by austinhedrick548** [kelseyp/munch#46]
Create a design document laying out an item card and details about its constituent parts.

**Comment by NathanaelPaulus** [comment]
So upon further research, I believe we should implement this component from material UI:
"Complex Interaction" Card
https://mui.com/material-ui/react-card/#complex-interaction

I think using parts of that card code and this code will do what we want:
"Media" Card
https://mui.com/material-ui/react-card/#media

**Comment by NathanaelPaulus** [comment]
This is mainly just summarizing the design combination of the two card components mentioned above. I think this is totally doable from a frontend side. If we can write the logic for the database info to reach the card itself, we should be good to go.

![Image](https://user-images.githubusercontent.com/123440471/228112618-e25915fc-6532-49c5-aa35-7bf65e3b9736.JPG)

**Comment by NathanaelPaulus** [comment]
Make a demo of the card using the sandbox mode for now.

**Comment by austinhedrick548** [comment]
Looks good. I like that there are options here, may need time to implement each button you are pointing out here, but can be doable over multiple sprints
