### ISSUE TITLE
TASK - Create UI design for main page

### ISSUE THREAD

**Issue by kelseyp** [kelseyp/munch#9]

**Comment by NathanaelPaulus** [comment]
Posted the images with more description in the discord, but I can add them here as well. Let me know!


View 1 (Main page with search)

![Image](https://user-images.githubusercontent.com/123440471/219135036-a6288f3a-bbd6-45bd-93b8-1c6fdd261276.jpg)


View 2 (Focused view on the item clicked)

![Image](https://user-images.githubusercontent.com/123440471/219135049-424e7f7c-ba95-4a0c-98fb-dbfdf7a90218.jpg)


View 3 (Nutritional info, clicked within view 2)

![Image](https://user-images.githubusercontent.com/123440471/219135070-4affc871-1ce8-4264-8a23-285da067e43d.jpg)


View 4 (Review info, clicked within view 2 or 3)

![Image](https://user-images.githubusercontent.com/123440471/219135084-9d28c8a4-1531-4bc6-b091-7301f5f40d24.jpg)

**Comment by NathanaelPaulus** [comment]
Current Documentation:


[Sprint 1 Task - Create UI Design.pdf](https://github.com/kelseyp/munch/files/10787382/Sprint.1.Task.-.Create.UI.Design.pdf)
